### PR TITLE
allow customizable label width for grid layout

### PR DESCRIPTION
**Pull request by jstnlth**
Previously the labels in the grid were basically unreadable - LibreOffice apps being an excellent example.  This patch allows a user to enter a numeric label length, so there is full customization by the user for any label width he wants.  Reasonable choices are offered via the settings menu, but any size can be set using gsettings or dconf-editor.
    
A label size of 0 is offered to disable labels completely.  This could be good for compact view - where the label was generally useless anyway. The name and description of each icon still shows up in the info bar.

### CODE REVIEW

**Comment by The-Panacea-Projects** [comment]
Okay interesting, didn't think it necessary but in anycase seems quite useful as an option. Will merge shortly after reviewing the code a bit.

**Comment by jstnlth** [comment]
On 22/01/16 07:53, The Panacea Projects
      wrote:
    
    
      Okay interesting, didn't think it necessary but in anycase
        seems quite useful as an option. Will merge shortly after
        reviewing the code a bit. 
      
        
          
          
        
        
      
    
    You are OK with not being able to see the name of the application on
    the label?  The LibreOffice labels are ALL LibreOf....  How can you
    tell them apart?   A minimal label length might be OK for a power
    user who already knows everything about the computer and just needs
    a tiny hint, but for most users they would want to be able to see
    most - if not all - of the name.
    
    That was the prime motivation behind the change.  Removing the label
    was added simply because it was an easy possibility based on the
    fix's design, allowing another level of customization to the end
    user.
    
    Thanks for making Gnomenu.  It makes gnome-shell almost usable.
    Justin

**Comment by The-Panacea-Projects** [comment]
Hi Justin appreciate the patch and yes we do agree for the most part that a full label would be useful for users  unfamilier with certain Apps and their function. It's just that we are of the opinion that the List-View better facilitates this need more so than a Grid, given the amount of horizontal space some labels would encompass. We are more inclined to incorperate a tooltip adjacent to each icon when hovered, offering all the information currently shown in the App-Box below (name & discreption). However time has not facilitated such a move and the option to manually adjust presented here seems useful in this regard.

**Comment by jstnlth** [comment]
On 22/01/16 09:08, The Panacea Projects
      wrote:
    
    
      Hi Justin appreciate the patch and yes we do agree for the most
        part that a full label would be useful for users unfamilier with
        certain Apps and their function. It's just that we are of the
        opinion that the List-View better facilitates this need more so
        than a Grid, given the amount of horizontal space some labels
        would encompass. We are more inclined to incorperate a tooltip
        adjacent to each icon when hovered, offering all the information
        currently shown in the App-Box below (name & discreption).
        However time has not facilitated such a move and the option to
        manually adjust presented here seems useful in this regard. 
      
        
          
          
        
        
      
    
    I prefer the list view myself.  Your tooltip idea could work well
    with this patch.  If the user chooses zero sized labels, then you
    could enable the tooltip.
    
    I don't like the workspaces replacing the categories panel when
    Recent/websites is chosen, so I think I'll work on seeing what a
    good option is for that.  I think the workspaces pane is also
    trigger by some other event - it seems to show up unexpectedly
    sometimes.   We would also like to have right-click options
    (add/remove from favorites/frequent and perhaps other choices), but
    that looks a bit complicated to code.
    
    Justin

**Comment by jstnlth** [comment]
On 22/01/16 07:53, The Panacea Projects wrote:
>
> Okay interesting, didn't think it necessary but in anycase seems quite
> useful as an option. Will merge shortly after reviewing the code a bit.
>

Just rethinking the label sizes again.  The number selection chosen was
semi-random.   Perhaps it would be more consistent to use multiples of
8  (so 112 and 128)

**Comment by The-Panacea-Projects** [comment]
Yes adding the tooltip along with the options this patch affords should 
suffice. Regarding the workspaces our current thinking is to unhinge 
from categories altogether and have it optionally shown to the right of 
menu (see pic). Its full width would only be shown when hovered unless 
otherwise requested.

**Pull request merged**
