### PR TITLE
Added missing strings to po file and updeted Russian translation.

### PR DESCRIPTION
**Pull request by vantu5z**

### CODE REVIEW

**Comment by The-Panacea-Projects** [comment]
Thanks for catching the missing strings in the en_US.po. This was an oversight that should have been fixed a few versions back.

**Comment by vantu5z** [comment]
Why don't you merge this pull request?

**Comment by The-Panacea-Projects** [comment]
Sorry, I got sidetracked. I've been working on a script to strip out the strings that need to be translated from the js code. I'll merge things afterward.

**Comment by The-Panacea-Projects** [comment]
Sorry about taking so long to merge this. The script I created, though, works and I was able to find an additional string that needs to be translated. I've copied it below, but you can find it in the latest po files I just uploaded into the master branch.

"Invalid accelerator. Try F12, <Super>space, <Ctrl><Alt><Shift>a, etc."

Thanks for your interest in Gno-Menu .. I really do appreciate the help.

**Pull request merged**
