### PR TITLE
allow gnomenu preferences/settings button to be hidden

### PR DESCRIPTION
**Pull request by jstnlth**
DEFAULT: ALL
    Always show the settings button
    
    OPTION: NONE
    Never show the settings button
    
    OPTION: <unix-group>
    Only show the settings to the members of this group.  "sudo" would be
    a good example for debian based systems, and would be my recommended
    default except that I understand that distros like Fedora and OpenSuse
    don't have a sudo group.
    
    This is a "hidden" option since it is not included in prefs.js.
    This prevents a user from mistakenly locking himself out of
    gnomenu's preferences.
    
    In order to be able to manage this via gsettings/deconf-editor, the
    schema must be copied into /usr/share/glib-2.0/schemas.
    Alternatively an administrator could change the default in the
    extensions ./schema folder and recompile with glib-compile-schema ./schema.

### CODE REVIEW

**Comment by The-Panacea-Projects** [comment]
We are not too clear on the premis for this patch as its not immediatly clear to us the circumstances that would culminate in one "mistakenly locking himself out of gnomenu's preferences" . Would you care to eloborate a bit more on this ?

**Comment by The-Panacea-Projects** [comment]
Not sure what happend there but closing wasn't intentional, still awaiting response.

**Comment by jstnlth** [comment]
The whole point of the patch is to "allow gnomenu preferences/settings button to be hidden".  If we are force to use Gnome-Shell for our next release, we intend to ship with gnomenu enabled to bring a bit of usability back to gnome-shell.  Our user-base is not computer savvy - many of them never having seen a computer before this.  We want the ability for an administrator to disable the settings button being prominently displayed in the menu system.  It seemed like a setting that many administrators might appreciate and so I am proposing it upstream.

I wasn't planning on adding this to prefs.js right from the beginning because I don't want to clutter up the settings menu.  This is an administrator-style setting after all, not an individual-style setting.  A clueless user could easily change the group name to something invalid (spelling error, whatever) and if the menu button was the only way they knew how to access the settings, they would have effectively locked themselves out of the settings.

**Comment by jstnlth** [comment]
A bit more clarity.   I did NOT want to write the patch as "hide the settings from the casual user group".  Most basic users will only be in the "users" group, but so would the power users - so there isn't a good existing group to block.  Instead, the patch is written as "show the settings only to the power users group."  Since power users will already belong to an extra group like sudo or adm, the system administrator wouldn't need to do anything silly like add a new group just to allow/disallow access to gnomenu settings.

Since it is written as "show to this group", specifying an invalid group will prevent anyone from seeing the settings button.

There are LOTS of ways to get at the settings (gsettings, dconf-editor, tweak-tool, gnome-shell-extension-prefs), but none of these will be familiar to a casual user.

**Pull request merged**
